### PR TITLE
Support ClojureScript compilation of metaprob.state and metaprob.state-test

### PR DESCRIPTION
**Pull request by zane**
## What does this do?

Adds support for compiling the `metaprob.state` and `metaprob.state-test` namespaces to JavaScript via the ClojureScript compiler:

* Modifies `metaprob.state` and `metaprob.state-test` to be valid Clojure / ClojureScript and renames them from `*.clj` to `*.cljc`. `.cljc` is the extension Clojure tooling expects for cross-compileable Clojure code.
* Adds a `cljstest` `make` target that runs a new ClojureScript test suite (currently just the tests in `metaprob.state-test`).
* Modifies the `test` `make` target to also run the new ClojureScript test suite.
* Adds entries to the `.gitignore` file for JavaScript artifacts generated by the ClojureScript compiler.
* Reorganizes some of the other entries in `.gitignore`.
* Adds a `cljsclean` `make` target that destroys JavaScript artifacts generated by the ClojureScript compiler.

### Pros
…

### Cons
…

## How do I test this?

1. Run the tests via `make test` (or, to just run the ClojureScript tests, `make cljstest`).
2. Start a ClojureScript REPL with `clj -Acljs -m cljs.main -re nashorn --repl` (or `-re node` if your system has node installed, and try requiring and working interactively with `metaprob.state` at the REPL:
```
cljs.user=> (require 'metaprob.state)
cljs.user=> (metaprob.state/empty-state)
{}
```

### CODE REVIEW

**Comment by jar600** [comment]
I looked over the diff. Looks fine to me. This message constitutes my review.

**Comment by alex-lew** [comment]
> Modifies metaprob.state and metaprob.state-test to be valid Clojure / ClojureScript and renames them from *.clj to *.cljc. .cljc is the extension Clojure tooling expects for cross-compileable Clojure code.

Were there any changes to `metaprob.state` to make it valid Clojure/ClojureScript? It looks like the renaming was all that happened? (If so, that's awesome!) The diff looks good to me :+1:

**Comment by zane** [comment]
@alex-lew Yep! No changes for this one! That, along with the fact that it has no dependencies of its own, is why I started with it. ☺️

**Comment by jar398** [comment]
Speaks to #14

**Pull request merged**
