### PR TITLE
Metaprob rewrite (another one!)

### PR DESCRIPTION
**Pull request by alex-lew**
This branch contains a new implementation of Metaprob.

### Breakdown of the new code
The Metaprob implementation now consists of the following parts:

**Utilities (written in Clojure)**
`metaprob.code-handlers` implements helper functions for dealing with Metaprob S-expressions
`metaprob.trace` implements the trace datatype and a number of operations on traces

**Core language**
`metaprob.generative-functions` implements Metaprob's core abstraction: the generative function. It provides a general constructor `make-generative-function` for generative functions, and two additional constructs that desugar to `make-generative-function` calls: the `gen` macro, and the `make-primitive` helper.

**Libraries**
`metaprob.prelude` exposes useful math functions like `log` and `exp`, as well as eager, generative-function versions of higher-order functions like `map` and `replicate`.
`metaprob.distributions` implements several common distributions as generative functions.
`metaprob.inference` implements the Metaprob standard inference library.

**Syntactic transformations**
`metaprob.expander` exposes the `mp-expand` helper function, which authors of Metaprob macros / static analyses can call. It desugars any generative function source code into a small core language consisting only of variables, literals, function calls, `quote` forms, `if` expressions, and `gen` expressions.
`metaprob.autotrace` implements an `autotrace` macro that relies on `mp-expand`. `(autotrace (gen [] ...))` creates an autotraced generative function.

---
### Very quick overview of language changes

Metaprob source files will typically begin with something like

```clojure
(ns my.project
  (:refer-clojure :exclude [map replicate apply])
  (:require [metaprob.trace :refer :all]
            [metaprob.prelude :refer :all]
            [metaprob.distributions :refer :all]
            [metaprob.generative-functions :refer :all]
            [metaprob.inference :refer :all]))
```

In their project, Clojure code can be used as usual. To define a generative function, users can:

- Call `make-generative-function` manually, passing in two arguments:
   * `run-in-clojure`, a Clojure function that accepts arguments and returns a value
   * `make-constrained-generator`, a Clojure function that accepts an _observation trace_ and returns a _constrained generator_ (see below for more details).
   * Optionally, the user can pass in a map of arbitrary metadata to attach to the generative function, e.g., `{:support [true false]}`.

- Call `make-primitive`, passing in a _sampler_ `(fn [& args] ...)` and a _scorer_ `(fn [val args] ...)`. The scorer returns the log probability mass or density of `val` under the distribution on return values induced by `(apply sampler args)`.

- Use the `gen` macro:
   * The simplest form of the `gen` macro is `(gen [& args] body...)`. This is a generative function in which no choices are traced.
   * A name can be given to the `gen` function (e.g., for recursive calls) using either `(gen my-name [& args] body...)` or `(gen {:name my-name} [& args] body...)`.
   * In general, the user may provide an optional _annotations map_ immediately following the keyword `gen` and preceding the argument list. These annotations are stored as part of the resulting generative function object's metadata, accessible via Clojure's `meta` function.
  * Within a `gen` body, traced random calls can be made in three ways: `(at addr other-generative-function arg1 arg2...)`, `(apply-at addr other-generative-function [arg1 arg2...])`, and `(let-traced [x (some-generative-function arg1 arg2...)] ...)`. 

A generative function can be run like an ordinary Clojure function, but also supports another operation, `make-constrained-generator`, which accepts an observation trace and returns a _constrained generator_. A constrained generator is a generative function with the following properties:

- Its inputs are the same inputs as the original generative function from which it was derived.
- It returns a triple `[value trace score]`, such that `trace` is a complete trace of the original generative function from which it was derived, `value` is the corresponding return value, and `score` is a log importance weight.
- As a generative function, it makes a number of traced choices. The requirement is that _its_ trace, when merged with the observation trace, is a supertrace of the trace it returns.

`infer-and-score` is implemented in terms of `make-constrained-generator`.

---
The examples in the `metaprob.examples` namespaces have been updated to use the new syntax, as have all the tests. They pass! 

However, we should decide:
- Whether to add new examples / remove some of the old ones.
- Whether to add new tests that give good coverage of Metaprob's language features, and remove some of the old ones.
- How to update the various `.md` files (documentation) that are out of date.
- Whether to move tutorials and Jupyter support into another repository.

### CODE REVIEW

**Comment by alex-lew** [comment]
It is annoying that source files have to start with

```
(:refer-clojure :exclude [map replicate apply])
```

One possible solution: the `gen` macro itself could insert a `(let [map metaprob.eager/map, replicate metaprob.eager/replicate, ...] ...)` around the body of a function. Outside of generative functions, there's no need for a special special `map` or `replicate`, so users could just use the Clojure versions.

@zane @joshuathayer Curious to hear what you all think of this possibility.

**Comment by zane** [comment]
@alex-lew If the best practice is to replace `clojure.core/map` with `metaprob.eager/map` I would prefer that it happen explicitly, in the `ns` form, rather than implicitly via the `gen` macro. Otherwise it will be too confusing for people coming to Metaprob from Clojure.

**Comment by zane** [comment]
@alex-lew If the goal is to provide an eager `map` could we encourage users to use `clojure.core/mapv` instead? No `:refer` needed! One thing to note about `clojure.core/mapv` is that the output type is always a vector, regardless of what the input type was.

**Comment by zane** [comment]
@alex-lew Another thing to note is that in ClojureScript, [`:refer :all` is not available](https://groups.google.com/forum/#!msg/clojurescript/SzYK08Oduxo/MxLUjg50gQwJ). We're going to need to recommend users do one of the following:

1. `:refer` every "core" Metaprob function individually.
2. Use namespace aliases, for example `(:require [metaprob.math :as math])` `(math/exp 10 2)`
3. Include different `ns` boilerplate in ClojureScript.

I pretty strongly prefer the second option. It's the Clojure community best-practice [[1](https://github.com/bbatsov/clojure-style-guide#prefer-require-over-use)] [[2](https://stuartsierra.com/2016/clojure-how-to-ns.html)], and referring each symbol individually would result in ginormous `ns` boilerplate.

**Comment by alex-lew** [comment]
@zane 

So, within a generative function, lazy versions of `map`, `map-indexed`, `reduce`, `repeatedly`, etc. are dangerous for subtle reasons. I don't think we want Metaprob users to have to reason about when it's ok or not ok to use laziness.

It's interesting that `mapv` is eager, but I don't think that's a solution -- because there's no analogue for `map-indexed`, `reduce`, etc.

Can you say more about what might be confusing to Clojure programmers about replacing `clojure.core/map` with `metaprob.eager/map` inside of `gen` bodies? I am thinking that `metaprob.eager/map` would be implemented something like this:

```clojure
(defn map [& args]
  (doall (apply clojure.core/map args)))
```

so the only way for it to bite you would be if you were _relying_ on laziness inside your generative function (which we want to avoid).

I do agree it's not a particularly clean implementation, though...


Re: `refer`, I could be convinced, but am not yet. It seems like core.logic and anglican, two other Clojure libraries that are trying to be "languages," both instruct users to `:use` them and gain full access to the language's functionality. In `core.logic`, you don't write

```
(logic/run [q]
  (logic/fresh [x]
    (logic/== x q)))
```

just

```
(run [q]
  (fresh [x]
     (== x q)))
```

I don't think users should have to remember that `log` is provided _by Metaprob_ (and what's the purpose of having a `metaprob.math` when all those math functions are provided by other libraries anyway)?

I can imagine creating a namespace that just exposed names from all the other namespaces, and importing it as something short like `m` or `mp` in Clojurescript code -- then you'd use, e.g., `mp/trace-value` and `mp/infer-and-score` and `mp/importance-resampling`. But I don't like the idea of `trace/trace-value`, `gen-func/infer-and-score`, and `inference/importance-resampling`: remembering what function comes from where is a big burden to place on users.

**Comment by zane** [comment]
> I can imagine creating a namespace that just exposed names from all the other namespaces, and importing it as something short like m or mp in Clojurescript code -- remembering what function comes from where is a big burden to place on users.

I was heading there, and agree!

**Comment by alex-lew** [comment]
Great :) Do you know if there's a way to have `gen` (the macro) exposed in the same namespace?

So people could do

```clojure
(ns my.project 
  (:require [metaprob.core :as m :refer [gen]]))
```

Not sure how to re-expose a macro that's implemented somewhere else.

**Comment by zane** [comment]
That syntax should work as-is, if I remember, and is how I would do it! 🙂 It would be a little different in ClojureScript (you'd probably use `:refer-macros`).

**Comment by alex-lew** [comment]
Ah, yes, that syntax should work, but the part I was wondering about is how `metaprob.core` (our giant namespace) would expose a `gen` macro that was actually defined in `metaprob.generative-functions` :-) 

But I just found https://github.com/ztellman/potemkin, which has an `import-vars` feature that seems to exist for just this purpose.

**Comment by zane** [comment]
Oh, sorry. I misunderstood!

Yes, I had imagined that we would use Potemkin. But now that I'm looking at it I'm not sure it supports ClojureScript. Will look into it further.

**Comment by zane** [comment]
You're right that it's not uncommon to refer a few core functions macros from libraries that implement embedded language (like `core.logic`). `gen`, `letgen`, and perhaps `infer` seem like a prime candidates for this. But in my experience referring to functions via aliases is pretty strongly preferred among Clojure programmers. I would draw the line before referring something like `replicate`, personally.

**Comment by alex-lew** [comment]
I think there are two questions:
- where to draw that line in general (i.e., do we include distributions like `flip` and `gaussian` and `uniform`? trace operations like `trace-value`?)
- what to do about `map`, `reduce`, `replicate`, etc.

In the second, the problem is that people will likely, out of habit, call the Clojure versions of these functions inside a `gen` form, which will cause hard-to-debug failures -- running `infer-and-score` might return an empty trace, for instance. How can we effectively prevent this?

**Comment by zane** [comment]
> So, within a generative function, lazy versions of `map`, `map-indexed`, `reduce`, `repeatedly`, etc. are dangerous for subtle reasons.

I understand, but I don't think rebinding `map` within `gen` bodies is the solution. Swapping out the function they intended to use will confuse users who have prior experience with Clojure. They might be surprised to find a different function than the one they intended to use in stack traces, for example.

If we want to take a hard line there it would be better to force the programmer to fix the issue proactively rather than try to fix the problem for them reactively behind the scenes. We could have `gen` error out if it finds symbols that refer to lazy functions in its body for example.

**Comment by alex-lew** [comment]
Hmm, I see. What about inserting a `doall` in front of all calls to lazy functions?

**Comment by zane** [comment]
That's certainly an option! I'm wary of that route because I'm worried that it will cause a divergence between what experienced Clojure programmers think is happening ("This expression will return a lazy sequence!") and what is actually happening ("This expression will return a fully realized list."). 

We also can't anticipate the full set of lazy functions that people might use. What if they get used to the behavior of implicitly `doall`-wrapped functions from `clojure.core` but then later get bitten by some lazy function that they've written themselves (or that they got from a library)? Better for them to get an error from their first naive use of `clojure.core/map` and thereafter know to be wary of laziness.

**Comment by zane** [comment]
@alex-lew and I discussed this a bit more on Slack, and at this stage my preferred way to protect users from the unintended consequences of laziness+tracing are, in order:

1. Providing eager versions of `clojure.core` functions in a special namespace and encouraging users to use them via an alias. (e.g. `(:require [metaprob.tracesafe :as tracesafe])` `tracesafe/map`

**Comment by alex-lew** [comment]
I think I'd be happy merging this, if @zane and @joshuathayer think we can go ahead. Things to resolve in the future:
- What is the best name for `make-constrained-generator`?
- How should we enforce eager evaluation of code that makes random choices inside of a `gen`? (what Zane and I were discussing above).

**Pull request merged**
