### PR TITLE
Add Docker image

### LINKED ISSUE #60: Clarify current directory setting in jupyter setup
File src/metaprob/tutorial/README.md is unclear about what directory to do these steps in. Since 2, 3, and 4 all talk about the `lein` command, they really ought to happen in the same directory. And because of step 4, that directory has to be the root of the clone.

So, we need to say that before step 2.

It would be nice if the setup were compatible with the 'normal' metaprob install, which currently moves `lein` to `bin/lein`, but we could change that...

### PR DESCRIPTION
**Pull request by zane**
## What does this do?
1. Adds files for building and manipulating a Docker image that, when run, starts Jupyter with all the necessary prerequisites for running the tutorial pre-installed.
2. Adds `make` targets for building and manipulating the above.
3. Modifies `.travis.yml` such that tests are run inside of a Docker container.
4. Fixes #60.

## Why should we do this?
As we've discovered recently installing Leiningen and other dependencies can be an error-prone process on some systems. Having a Docker image should make starting the tutorial painless for people who already have `docker` and `docker-compose` installed.

## How can I test this?

1. Install Docker on your system and ensure that `docker` is on your path.
2. Check out this branch.
3. `make docker-build`
4. `make docker-test`
5. Follow the instructions in the tutorial `README` to launch it.
6. Open the tutorial.
7. Try to run the first cell.

### CODE REVIEW

**Comment by alex-lew** [comment]
This looks neat! In the tutorial/README, perhaps we should specify which directory those commands should be run from? The README is in the tutorial directory, but you want to run the commands from the root directory of the repo, right?

Also, do you think we could add a `jupyter-lab` version? It's a nicer interface! (I could do this after this PR is merged if you'd like.)

**Comment by zane** [comment]
@alex-lew Great suggestions!

Yes, you'd need to run the commands from the same directory as the `Makefile`. I'll add that documentation to this pull request.

Jupyter Lab support would be a natural candidate for a subsequent pull request! The only reason why I didn't include it is because this pull request is big as-is. 😅

Another thing we could do would be to automatically publish these images to Docker Hub. That would allow anyone who has Docker installed to run the tutorial with a single command. They wouldn't even need to have cloned the repository.

**Comment by zane** [comment]
@alex-lew I had to add a couple more steps to the tutorial `README` since it turns out it's not possible to have Jupyter open a URL a browser on the host automatically.

I'd like to get a second pair of eyes on it. If everything looks good to you (and you can successfully run the "How can I test this?" section of this pull request's description) then feel free to merge! :shipit:

**Comment by joshuathayer** [comment]
I caught this up to master, updated the tutorial README to address the issues above, ensured tests pass, and ensured that the tutorial runs as expected. Giving this the :shipit:

**Pull request merged**
